---
# Include variables and define needed variables.
- name: Checking Ansible version...
  fail:
    msg: "\n\n😱  You need at least version 2.0 of Ansible to continue.\n"
    when: not ansible_version.major == 2

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

#- include: setup-Suse.yml
#  when: ansible_os_family == 'Suse'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'
