---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  
# Setup/install tasks.
- include: setup-RedHat.yml
  # when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  when: ansible_os_family == 'RedHat'

# - include: setup-Fedora.yml
#   when: ansible_distribution == 'Fedora'

#- include: setup-Suse.yml
#  when: ansible_os_family == 'Suse'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'
