---
# tasks file for be-id
- name: Download eid repo
  get_url:
    url: "{{ eid_url }}"
    dest: "/tmp/eid-archive_{{ eid_version }}_all.deb"
  register: eid_download

- name: Install eid repo
  apt:
    deb: "/tmp/eid-archive_{{ eid_version }}_all.deb"
    state: installed
  when: eid_download | succeeded
  register: eid_install
  notify:
    - clean up temp files
    - run apt-get update

- meta: flush_handlers

- name: Install eid packages
  apt:
    name: "{{ item }}"
    state:  present
  with_items:
    - "{{ eid_packages }}"
  when: eid_install | succeeded

- name: Install Java browser plugin
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ eid_browser_packages }}"
  when: eid_install | succeeded
